### ISSUE TITLE
Autorename option in file move endpoint

### ISSUE THREAD

**Issue by leoasis** [Jesus/dropbox_api#11]
I'm looking forward to using this client but it seems not all the allowed parameters can be passed to the methods. In particular I'm looking forward to the `autorename` param in the files_move endpoint (https://www.dropbox.com/developers/documentation/http/documentation#files-move).

Maybe we could add a third parameter in this endpoint with an hash that would allow to pass all the non required parameters.

What do you think? Any other approach to allow these other params?

**Comment by leoasis** [comment]
I've just found that the exact same approach is being followed in the `upload` endpoint: https://github.com/Jesus/dropbox_api/blob/master/lib/dropbox_api/endpoints/files/upload.rb. It is receiving the other non required params as `options`, but for some reason they are not being used in the `perform_request` method.

**Comment by leoasis** [comment]
Thank you for fixing this 💃

**Comment by Jesus** [comment]
Thank you for the good issue report :)
