### ISSUE TITLE
Chunked Uploads

### ISSUE THREAD

**Issue by rrv4813** [Jesus/dropbox_api#14]
I want to upload files in chunk using /upload_session/* endpoints.
It seems that this has not been implemented as per http://www.rubydoc.info/gems/dropbox_api/file/api_coverage.md , 

but there's a comment "Do not use this to upload a file larger than 150 MB. Instead, create an upload session with #upload_session_start()." in upload.rb which is creating the confusion, BTW I was not able to see the implementation of upload_session_start() so I assume it is not implemented till now.

Am I missing something?

**Comment by Jesus** [comment]
You're correct, the `upload_session_*` endpoints haven't been implemented yet.

Hopefully I'll be able to add them soon.

**Comment by rrv4813** [comment]
Thanks Jesus!
Much appreciated.

**Comment by Jesus** [comment]
I'm glad to announce that [latest version (0.1.5)](https://github.com/Jesus/dropbox_api/releases/tag/v0.1.5) includes an implementation of the following endpoints:

  * `upload_session/start`
  * `upload_session/append_v2`
  * `upload_session/finish`

Which should be enough to allow big uploads.
