### ISSUE TITLE
Rubydoc does not show the endpoint documentation

### ISSUE THREAD

**Issue by LikeLakers2** [Jesus/dropbox_api#17]
Hi there, I'm planning to use this gem because it seems pretty complete, or at the least, it has all the methods I need to make my own syncing script for a Discord bot I'm making.

I noticed over on the [rubydoc for this gem](http://www.rubydoc.info/gems/dropbox_api/0.1.5/) that the documentation for the endpoint methods does not appear for *all* endpoints. Some, such as CreateFolder, will have their methods appear -- but others like Upload do not!

I searched a little into this and I found eb13f3321bc7777c7bf73f4f3ff49b1053f93792, a commit where all the `# @method` stuff was replaced with a YARD plugin. So I looked at the documentation that rubydoc.info had for v0.1.4 of this gem, and lo-and-behold, all the endpoint documentation was there without error.

I don't know what to make of this, I think it's worth looking into however.

**Comment by Jesus** [comment]
Hi, the problem is that the online documentation can't use the plugin I wrote to generate the documentation.

That's something I'm working to sort out.

**Comment by Jesus** [comment]
I've published the documentation at: http://jesus.github.io/dropbox_api/

I've decided to stop using rubydoc.info so I could keep using the custom plugins. I hope you find this useful.

Please file another issue if you have further troubles to understand the documentation.
