### ISSUE TITLE
Ability to revoke a token

### ISSUE THREAD

**Issue by jagthedrummer** [Jesus/dropbox_api#33]
It looks like there's currently no ability to revoke a token once a user has completed the OAuth flow. I can look into adding it if that's something you'd accept in a PR.

**Comment by Jesus** [comment]
Sure, any PR that helps completing the full Dropbox API coverage is more than welcome.

**Comment by Jesus** [comment]
If you submit that patch, it'll be more than welcome. I'll close this for now.
