### ISSUE TITLE
JSON::GeneratorError: only generation of JSON objects or arrays allowed

### ISSUE THREAD

**Issue by atroppmann** [Jesus/dropbox_api#36]
Hi there,

I get the error message "_JSON::GeneratorError: only generation of JSON objects or arrays allowed_" after trying to collect account data:

`client = DropboxApi::Client.new(DROPBOX_TOKEN)`
`client.get_current_account`

I already tried to switch to a different version of _execjs_ gem without success.

Using _ruby 2.1.7_ and _json_pure 2.1.0_ for my Rails application.

Did you see this error behaviour in any context before?

Greetings, Alex

**Comment by Jesus** [comment]
I haven't tried to use this gem with `json_pure`.

Could you send the full backtrace?
