### ISSUE TITLE
Using Stone to generated routes and data types

### ISSUE THREAD

**Issue by braincore** [Jesus/dropbox_api#4]
Thanks for creating a Ruby SDK. You'll notice that our other official SDKs use a library called [Stone](https://github.com/dropbox/stone) to generate routes and data types, which makes keeping up-to-date with all our API changes easier as we regularly update our [specs repo](https://github.com/dropbox/dropbox-api-spec). Unfortunately, we don't have a Ruby generator, but this is a light tap that we would be delighted if a 3rd party made one :)

**Comment by Jesus** [comment]
Sounds like a suggestion to an interesting project. Unfortunately, I don't have the time to develop & maintain such generator.

Also, the final goal of this SDK is not only to be a one-to-one mapping to all endpoints but also to create abstractions to provide a better experience for the library user. A good example where these abstractions will be useful is on the `/upload_session/*` endpoints.

Though we're still far from that, so any help would be much appreciated.
