### ISSUE TITLE
Get Shared Links only shows 200 files

### ISSUE THREAD

**Issue by darkrubyist** [Jesus/dropbox_api#42]
Hi,

I have recently used Get Shared Links method but is only returning 200 files. In the app folder, I had 2000 files. How can I get all of them?

Kind Regards
Andrew

**Comment by apurvis** [comment]
http://www.xuuso.com/dropbox_api/DropboxApi/Results/ListSharedLinksResult.html#has_more%3F-instance_method

**Comment by darkrubyist** [comment]
Thank you very much for your reply. I finally figured out how to do it. The `list_folder_continue` method doesn't work for shared links when you are using a Folder App, because of permissions.

But I was able to pass the cursor to the method `get shared links` method and it works like a charm.

**Comment by apurvis** [comment]
resolve this then?

**Comment by darkrubyist** [comment]
Yes. Everything is ok now. Thank you very much.
