### ISSUE TITLE
List_folder result entries breaks for shared folder

### ISSUE THREAD

**Issue by milj** [Jesus/dropbox_api#50]
Hello,

I found an issue when trying to iterate through a publicly shared folder. The Dropbox API  [documentation](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) instructs to use the `shared_link` option of the  `list_folder` request. The dropbox_api gem (unknowingly, I guess) supports this option:
```
result = client.list_folder('', shared_link: 'https://www.dropbox.com/sh/cut/cut')
```
but I'm unable to iterate through the entries:
```
result.entries
ArgumentError: Invalid value for `path_lower`: nil.
	from /cut/dropbox_api-0.1.12/lib/dropbox_api/metadata/base.rb:62:in `rescue in []=`
```

I don't know it supporting shared folders is on the roadmap. I just wanted to let you guys know that it does not work.

Thanks!

**Comment by Jesus** [comment]
Thanks for reporting this, it should have been fixed by #55.
