### ISSUE TITLE
Please upgrade dependency faraday to ~> 0.17

### ISSUE THREAD

**Issue by chuntangwang** [Jesus/dropbox_api#67]
I have used the `dropbox_api 0.1.17` in my `fastlane` script.

Recently, my project upgraded `fastlane` version to latest that also upgraded `faraday` to `~> 0.17`.
It's caused the compatible issues of `faraday`.
See the changes. https://github.com/fastlane/fastlane/commit/cf2ac511faf48f2d81bc2ffa7d9a8336fe81e1c2

I restricted `fastlane` version on `2.133.0` that before the commit for now.

I'll appreciate If the project could upgrade faraday's version.

**Comment by williamweckl** [comment]
I'm with a similar problem with internal dependencies of my company.

**Comment by Jesus** [comment]
Thanks for reporting!
