### ISSUE TITLE
please use more reasonable faraday restriction, allow 1.0.1?

### ISSUE THREAD

**Issue by jrochkind** [Jesus/dropbox_api#71]
The gemspec currently says:

` spec.add_dependency "faraday", "<= 1.0"

https://github.com/Jesus/dropbox_api/blob/4c43dc78df3ab5ee95253580ce211ad2de4fe372/dropbox_api.gemspec#L26

That ends up meaning any faraday version less than or equal to 1.0.0, but no greater. 

This means 1.0.0 is allowed, but 1.0.1 released March 29 and [containing a few bugfixes](https://github.com/lostisland/faraday/compare/v1.0.0...v1.0.1) is *not* allowed by `dropbox_api`. An app using `dropbox_api` can use faraday 1.0.0, but not 1.0.1. 

I think this is probably not what you intended? Not sure what you intended? Perhaps `< 2.0`, meaning allow any 0.x and any 1.x? I would advocate that, I think?

Here is the commit where you changed gemspec to say `<= 1.0`, I'm afraid the commit message doesn't have much guidance. https://github.com/Jesus/dropbox_api/commit/71073700349cdfa14d8f31314c3ac7cf41c59ee3

**Comment by jrochkind** [comment]
Hi, what is the current maintenance situation for this gem? 

It is a problem for me that I have an indirect dependency on dropbox_api, and thus my app is unable to use faraday 1.0.1 or 1.1.0. I'd guess 1.0.1 has bugfixes, but I'm stuck on 1.0.0. 

Thanks for any advice!  I am considering forking this gem and/or trying to get my dependencies to move away from it.

**Comment by jlledom** [comment]
+1 to this, I'm stuck on [xero-ruby](https://rubygems.org/gems/xero-ruby) 1.1.0 because of this gem's dependency on faraday 1.0.

Thanks for your work @Jesus

**Comment by williamweckl** [comment]
Any updates on this one?
