### ISSUE TITLE
Please update search endpoint to use the v2 path

### ISSUE THREAD

**Issue by czhang-blurb** [Jesus/dropbox_api#74]
https://dropbox.tech/developers/search-files-using-the-dropbox-api

> We’ll be retiring the old v1 search on February 28th, 2021. If you haven’t already, please migrate to the search v2 endpoint at your earliest convenience.

https://github.com/Jesus/dropbox_api/blob/master/lib/dropbox_api/endpoints/files/search.rb#L4

The new version should be:

/2/files/search_v2

**Comment by czhang-blurb** [comment]
Hi @Jesus , just wanted to check again -- is this change to the search endpoint on your radar, and is it something you'd be able to update before Dropbox disables the endpoint on Feb 28th?

**Comment by Jesus** [comment]
How do you know v1 of the search endpoint will be deprecated on Feb 28th?

**Comment by czhang-blurb** [comment]
Thank you! 

The deprecation notice was posted here in October: https://dropbox.tech/developers/search-files-using-the-dropbox-api , and dropbox also emailed last month a warning email to everyone who was using the marked-for-deprecation endpoint, which was what originally drew it to our attention.

**Comment by Jesus** [comment]
I see, thanks!
