### ISSUE TITLE
Catching 401

### ISSUE THREAD

**Issue by aandis** [Jesus/dropbox_api#85]
The lib currently [throws](https://github.com/Jesus/dropbox_api/blob/5e5631b69b21031e27b50ed03cee2fee0206e71f/lib/dropbox_api/endpoints/base.rb#L37) a `DropboxApi::Errors::HttpError` with response code and response body as a string. There's no way to catch specific http error codes.

**Comment by aandis** [comment]
@Jesus if you think this is a valid problem, I'd be happy to make a pr to fix this. :)

**Comment by Jesus** [comment]
@aandis thanks for reporting this, I ended up doing it myself because I need it urgently to support refresh tokens.
