### ISSUE TITLE
file downloading

### ISSUE THREAD

**Issue by santoshkumar611** [Jesus/dropbox_api#9]
when downloading file, metadata of file object was generated but file content not generated ,
I searched methods on the file metadata object but i can't succed.

**Comment by Jesus** [comment]
The file content is yielded to the block. Example:

```ruby 
dropbox_client = DropboxApi::Client.new

File.open("local_file", "w") do |f|
  dropbox_client.download "/photo.jpg" do |chunk|
    f.write chunk
  end
end

```

**Comment by tommybstitch** [comment]
While trying to do this, I am getting `Encoding::UndefinedConversionError: "\xDD" from ASCII-8BIT to UTF-8` error. Any advice?

**Comment by codemicky** [comment]
Hi @Jesus, this worked but needs force encoding currently.

```
dropbox_client = DropboxApi::Client.new

File.open("local_file", "w") do |f|
  dropbox_client.download "/photo.jpg" do |chunk|
    f.write chunk.force_encoding("UTF-8")
  end
end
```
